package com.warehousepro.entity;

public enum PermissionName {
  AUTH_LOGIN,
  AUTH_LOGGED_IN,

  USER_CREATE,
  USER_UPDATE,
  USER_DELETE,
  USER_LIST,

  ROLE_CREATE,
  ROLE_UPDATE,
  ROLE_DELETE,
  ROLE_LIST,

  PERMISSION_ASSIGN,
  PERMISSION_REVOKE,

  INVENTORY_TRACK,
  INVENTORY_PRODUCT_CREATE,
  INVENTORY_PRODUCT_UPDATE,
  INVENTORY_PRODUCT_DELETE,
  INVENTORY_PRODUCT_LIST,
  INVENTORY_LOW_STOCK_ALERT,

  ORDER_CREATE,
  ORDER_UPDATE,
  ORDER_DELETE,
  ORDER_SEARCH,
  ORDER_LIST,
  ORDER_STATUS_TRACK,
  ORDER_ASSIGN_SHIPMENT,

  WAREHOUSE_CREATE,
  WAREHOUSE_UPDATE,
  WAREHOUSE_DELETE,
  WAREHOUSE_SEARCH,
  WAREHOUSE_LIST,
  WAREHOUSE_INVENTORY_DISTRIBUTE,
  WAREHOUSE_SPACE_OPTIMIZE,

  PROCUREMENT_SUPPLIER_CREATE,
  PROCUREMENT_SUPPLIER_UPDATE,
  PROCUREMENT_SUPPLIER_DELETE,
  PROCUREMENT_SUPPLIER_SEARCH,
  PROCUREMENT_SUPPLIER_LIST,

  PROCUREMENT_ORDER_CREATE,
  PROCUREMENT_ORDER_UPDATE,
  PROCUREMENT_ORDER_DELETE,
  PROCUREMENT_ORDER_SEARCH,
  PROCUREMENT_ORDER_LIST,
  PROCUREMENT_ORDER_STATUS_TRACK,

  SHIPMENT_CREATE,
  SHIPMENT_UPDATE,
  SHIPMENT_DELETE,
  SHIPMENT_SEARCH,
  SHIPMENT_LIST,
  SHIPMENT_TRACKING_VIEW,

  RETURN_CREATE,
  RETURN_UPDATE,
  RETURN_DELETE,
  RETURN_SEARCH,
  RETURN_LIST,

  AUDIT_LOG_VIEW,
  AUDIT_LOG_EXPORT,
}
