spring:
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET:your-access-secret}
    expiration: ${JWT_ACCESS_EXPIRATION:3600000}
  refresh:
    secret: ${JWT_REFRESH_SECRET:your-refresh-secret}
    expiration: ${JWT_REFRESH_EXPIRATION:86400000}

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        security: DEBUG
