version: "3.8"

services:
  warehouse-pro_postgres-db:
    container_name: "warehouse-pro_postgres_db_container"
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=mydatabase"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=myuser"
    ports:
      - "5432:5432"

  warehouse-pro_pgadmin-db:
    container_name: "warehouse-pro_pgadmin_container"
    image: "dpage/pgadmin4:latest"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    ports:
      - "5051:80"
    depends_on:
      - warehouse-pro_postgres-db
